<a href="https://colab.research.google.com/github/AKA333/pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()
import torch.optim as optim

In [ ]:
import torch

torch0d = torch.tensor(1)

torch1d = torch.tensor([1, 2, 3])

torch2d = torch.tensor([[1, 2], [3, 4]])

torch3d = torch.tensor([[[1, 2], [3, 4]], [[11, 12], [13, 14]]])

print(torch0d)

print(torch1d)

tensor(1)
tensor([1, 2, 3])


In [ ]:
print(torch1d.dtype)

torch.int64


In [ ]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]
                         ])

print(tensor2d)

print(tensor2d.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [ ]:
reshaped_tensor2d = tensor2d.reshape(3, 2)
print(reshaped_tensor2d)
print(reshaped_tensor2d.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [ ]:
tensor2d.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

Tensors as multi dimensional arrays

In [ ]:
# Initializing a tensor
data = torch.tensor([
    [0, 1],
    [2, 3]
])

print(data)

tensor([[0, 1],
        [2, 3]])


In [ ]:
data = torch.tensor([
    [5, 6],
    [7, 8]
], dtype= torch.float32)

print(data, type(data))

tensor([[5., 6.],
        [7., 8.]]) <class 'torch.Tensor'>


In [ ]:
data = torch.tensor([
    [0.11343, 4.555],
    [66.903, 3]
], dtype=torch.int32)

print(data, type(data))

tensor([[ 0,  4],
        [66,  3]], dtype=torch.int32) <class 'torch.Tensor'>


In [ ]:
zeros = torch.zeros(2, 3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
ones = torch.ones(2, 3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
rr = torch.arange(1, 10)
print(rr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
print(rr + 2)

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])


In [ ]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a = torch.tensor([
    [1, 2],
    [2, 3],
    [4, 5]
])

b= torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("A is:\n", a)
print("B is:\n", b)

print("product of A * B:\n", a @ b)

A is:
 tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
product of A * B:
 tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


In [ ]:
prod = a @ b
print(a.shape)
print(b.shape)
print(prod.shape)

torch.Size([3, 2])
torch.Size([2, 4])
torch.Size([3, 4])


In [ ]:
rr = torch.arange(1, 16)
print("current shape rr:", rr.shape)
print("rr:\n", rr)
print()
rr = rr.view(3, 5)
print("new shape rr:", rr.shape)
print("rr:\n", rr)

current shape rr: torch.Size([15])
rr:
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

new shape rr: torch.Size([3, 5])
rr:
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])


In [ ]:
data = torch.arange(1, 16, dtype=torch.float32).view(5, 3)
print("Data is:\n", data)

Data is:
 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])


In [ ]:
print("taking sum over columns")
print(data.sum(dim=0))

taking sum over columns
tensor([35., 40., 45.])


In [ ]:
print("taking sum over rows")
print(data.sum(dim=1).unsqueeze(1))

taking sum over rows
tensor([[ 6.],
        [15.],
        [24.],
        [33.],
        [42.]])


In [ ]:
print("taking sum over rows")
print(data.sum(dim=1, keepdim=True))

taking sum over rows
tensor([[ 6.],
        [15.],
        [24.],
        [33.],
        [42.]])


In [ ]:
print("taking stddev over rows")
print(data.std(dim=1, keepdim=True))

taking stddev over rows
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [ ]:
print("taking stddev over columns")
print(data.std(dim=0, keepdim=True))

taking stddev over columns
tensor([[4.7434, 4.7434, 4.7434]])


In [ ]:
data.sum()

tensor(120.)

In [ ]:
 data = torch.tensor([
     [1, 2.2, 9.6],
     [4, -7.2, 6.3]
     ])

 row_avg = data.mean(dim=1, keepdim=True)
 print(row_avg)

 col_avg = data.mean(dim=0, keepdim=True)
 print(col_avg)

tensor([[4.2667],
        [1.0333]])
tensor([[ 2.5000, -2.5000,  7.9500]])


In [ ]:
row_std= data.std(dim=1, keepdim=True)
print(row_std)

col_std = data.std(dim=0, keepdim=True)
print(col_std)

tensor([[4.6576],
        [7.2224]])
tensor([[2.1213, 6.6468, 2.3335]])


In [ ]:
x= torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
], dtype=torch.float32)
print(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [ ]:
x.shape

torch.Size([3, 2, 2])

In [ ]:
x[0]

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
x[0][1][1]

tensor(4.)

In [ ]:
x[:, 0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [ ]:
print(x[0].shape)

torch.Size([2, 2])


In [ ]:
x[:, :, 0]

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])

In [ ]:
x[:, :, 0].shape

torch.Size([3, 2])

In [ ]:
matr = torch.arange(1, 16).view(5, 3)
print(matr)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [ ]:
matr[[0, 2, 4]]

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]])

In [ ]:
x[:, 0, 0]

tensor([1., 5., 9.])

In [ ]:
x[:, :, 0]

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])

In [ ]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [ ]:
x[0, 0, 0]

tensor(1.)

In [ ]:
x[0, 0, 0].item()

1.0

Autograd- automatic differentiation package

In [ ]:
# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()

In [ ]:
# requires_grad parameter tells pytorch to store gradients during training we need the gradient and not during the inference

x= torch.tensor([2.], requires_grad=True)

pp.pprint(x.grad)

None


In [ ]:
# calculating gradient of y with respect of x
y= x * x * 3 #3x^2

y.backward()
print(x.grad)
pp.pprint(x.grad) # dy/dx = 6x

tensor([24.])
tensor([24.])


In [ ]:
if x.grad is not None:
  x.grad.zero_()
  print(x.grad)

z= x*x*3
z.backward()
pp.pprint(x.grad)

tensor([0.])
tensor([12.])


# Neural Network Module

In [ ]:
import torch.nn as nn

In [ ]:
input = torch.ones(2, 3, 4)
print("Input:\n", input)

# Make a linear layers tranforming n, h_in dimensional input to n, h_out
linear = nn.Linear(4, 2)
linear_output = linear(input)
linear_output

Input:
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[[ 0.4477, -1.2844],
         [ 0.4477, -1.2844],
         [ 0.4477, -1.2844]],

        [[ 0.4477, -1.2844],
         [ 0.4477, -1.2844],
         [ 0.4477, -1.2844]]], grad_fn=<ViewBackward0>)

In [ ]:
list(linear.parameters())

[Parameter containing:
 tensor([[-0.2252,  0.3761,  0.0583,  0.4209],
         [-0.1045, -0.1297, -0.3350, -0.3037]], requires_grad=True),
 Parameter containing:
 tensor([-0.1824, -0.4115], requires_grad=True)]

In [ ]:
linear_output

tensor([[[ 0.4477, -1.2844],
         [ 0.4477, -1.2844],
         [ 0.4477, -1.2844]],

        [[ 0.4477, -1.2844],
         [ 0.4477, -1.2844],
         [ 0.4477, -1.2844]]], grad_fn=<ViewBackward0>)

In [ ]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.6101, 0.2168],
         [0.6101, 0.2168],
         [0.6101, 0.2168]],

        [[0.6101, 0.2168],
         [0.6101, 0.2168],
         [0.6101, 0.2168]]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Use nn.Sequential to pass ouput of one to input as other rather than creating intermediate tensors

block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2, 3, 4)
output = block(input)
output

tensor([[[0.8166, 0.4702],
         [0.8166, 0.4702],
         [0.8166, 0.4702]],

        [[0.8166, 0.4702],
         [0.8166, 0.4702],
         [0.8166, 0.4702]]], grad_fn=<SigmoidBackward0>)

In [ ]:
block = nn.Sequential(
    nn.Linear(4, 8),     # Layer 1: maps 4 features -> 8
    nn.ReLU(),           # Activation function
    nn.Linear(8, 16),    # Layer 2: maps 8 features -> 16
    nn.ReLU(),
    nn.Linear(16, 2),    # Layer 3: maps 16 features -> 2
    nn.Sigmoid()         # Final output activation
)

input = torch.ones(2, 3, 4)
output = block(input)

pp.pprint(block)
pp.pprint(output)
print("Output shape:", output.shape)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=16, bias=True)
  (3): ReLU()
  (4): Linear(in_features=16, out_features=2, bias=True)
  (5): Sigmoid()
)
tensor([[[0.4921, 0.5315],
         [0.4921, 0.5315],
         [0.4921, 0.5315]],

        [[0.4921, 0.5315],
         [0.4921, 0.5315],
         [0.4921, 0.5315]]], grad_fn=<SigmoidBackward0>)
Output shape: torch.Size([2, 3, 2])


In [ ]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    super().__init__()

    self.input_size = input_size
    self.hidden_size = hidden_size

    self.model = nn.Sequential(
        nn.Linear(self.input_size, self.hidden_size),
        nn.ReLU(),
        nn.Linear(self.hidden_size, self.hidden_size),
        nn.ReLU(),
        nn.Linear(self.hidden_size, self.input_size),
        nn.Sigmoid()
    )

  def forward(self, x):
      output = self.model(x)
      return output

In [ ]:
# Or we can also do the above without using sequential as

class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    super().__init__()

    self.input_size = input_size
    self.hidden_size = hidden_size

    self.linear = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.hidden_size)
    self.relu2 = nn.ReLU()
    self.linear3 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear = self.linear(x)
    relu = self.relu(linear)
    linear2 = self.linear2(relu)
    relu2 = self.relu2(linear2)
    linear3 = self.linear3(relu2)
    output = self.sigmoid(linear3)
    return output

In [ ]:
# instantiating our class
input = torch.randn(2, 5)
print("Input tensor:", input)

model= MultilayerPerceptron(5, 3)

output = model(input)
pp.pprint(output)

print(output.sum(dim = 1, keepdim=True))

Input tensor: tensor([[ 0.1583,  0.9316,  0.7051,  2.1460, -0.6194],
        [ 0.7698,  1.1380,  0.4794,  0.5636,  1.9512]])
tensor([[0.4112, 0.3857, 0.5430, 0.4382, 0.6635],
        [0.4020, 0.3872, 0.5523, 0.4266, 0.6528]], grad_fn=<SigmoidBackward0>)
tensor([[2.4416],
        [2.4209]], grad_fn=<SumBackward1>)


In [ ]:
list(model.named_parameters())

[('model.0.weight',
  Parameter containing:
  tensor([[-0.3521, -0.0107,  0.2504, -0.2067, -0.2456],
          [-0.2181,  0.3880, -0.1964, -0.1435,  0.1549],
          [ 0.3751, -0.1781,  0.4134, -0.0600, -0.3729]], requires_grad=True)),
 ('model.0.bias',
  Parameter containing:
  tensor([-0.2770, -0.2475, -0.2937], requires_grad=True)),
 ('model.2.weight',
  Parameter containing:
  tensor([[ 0.0502, -0.5453, -0.5262],
          [ 0.2353, -0.4153,  0.2791],
          [-0.5560,  0.0345, -0.5042]], requires_grad=True)),
 ('model.2.bias',
  Parameter containing:
  tensor([ 0.4202, -0.3235, -0.5006], requires_grad=True)),
 ('model.4.weight',
  Parameter containing:
  tensor([[ 0.4552,  0.0420,  0.2561],
          [-0.0745, -0.5597,  0.1083],
          [-0.4532, -0.0160, -0.4342],
          [ 0.5648,  0.4909, -0.1611],
          [ 0.5718, -0.4078,  0.0859]], requires_grad=True)),
 ('model.4.bias',
  Parameter containing:
  tensor([-0.5503, -0.4340,  0.3627, -0.4859,  0.4387], requires_grad=

In [ ]:
import torch.optim as optim

In [ ]:
y = torch.ones(10, 5)

x= y + torch.randn_like(y)
x

tensor([[-0.5769, -0.2714,  1.7065, -0.3116,  1.9855],
        [ 0.4036, -0.8177,  1.3945,  2.0618, -0.4156],
        [ 1.5736,  0.4580,  1.0838,  1.6493,  2.2176],
        [-0.2020, -0.3378,  0.2244,  0.7490, -0.0697],
        [-0.8851,  1.6197,  0.2657,  1.3444,  0.0506],
        [ 2.4435,  0.2794,  1.0036,  0.4768, -0.6181],
        [ 0.7484,  0.6052, -0.9083,  0.7447, -0.2717],
        [ 2.4573,  0.7618, -0.6258,  0.8845,  1.4994],
        [ 1.3214,  1.4602, -0.5306,  0.1745,  2.0097],
        [ 1.3505,  1.8379,  1.1301,  0.1399,  2.1513]])

In [ ]:
model = MultilayerPerceptron(5, 3)

adam = optim.Adam(model.parameters(), lr = 1e-1)

loss_function = nn.MSELoss()

y_pred = model(x)
loss_function(y_pred, y).item()

0.37146130204200745

In [ ]:
n_epoch= 10

for epoch in range(n_epoch):
  adam.zero_grad()

  y_pred = model(x)

  # print(list(model.parameters()))

  loss = loss_function(y_pred, y)

  print("Epoch %d: train loss: %.4f" % (epoch, loss.item()))

  loss.backward()

  adam.step()

Epoch 0: train loss: 0.0000
Epoch 1: train loss: 0.0000
Epoch 2: train loss: 0.0000
Epoch 3: train loss: 0.0000
Epoch 4: train loss: 0.0000
Epoch 5: train loss: 0.0000
Epoch 6: train loss: 0.0000
Epoch 7: train loss: 0.0000
Epoch 8: train loss: 0.0000
Epoch 9: train loss: 0.0000


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 1.3141, -0.1864,  1.6086,  1.0366,  0.9829],
         [ 0.0651,  1.3595, -1.8247,  1.1069,  0.3676],
         [-0.1434, -1.0921,  0.1974,  0.3181, -0.5243]], requires_grad=True),
 Parameter containing:
 tensor([ 1.3037,  1.5841, -0.6128], requires_grad=True),
 Parameter containing:
 tensor([[-0.5140, -0.2403, -0.3265],
         [ 1.6308,  0.8053, -0.1252],
         [ 2.1872,  2.2788,  1.1970]], requires_grad=True),
 Parameter containing:
 tensor([-0.7651,  1.3723,  1.3935], requires_grad=True),
 Parameter containing:
 tensor([[0.1053, 0.9203, 2.0637],
         [0.4348, 1.8215, 1.6672],
         [0.3616, 1.4891, 1.9676],
         [0.0429, 1.3685, 1.2379],
         [0.7577, 1.3420, 1.3019]], requires_grad=True),
 Parameter containing:
 tensor([0.9207, 1.0158, 0.8929, 1.3271, 1.1828], requires_grad=True)]